_home_index:
    path:       /
    defaults:   { _controller: HomeWorkBundle:Index:index }

_test_twig:
    path:       /twig
    defaults:   { _controller: HomeWorkBundle:Index:twig }

_test_twig2:
    path:       /twig2
    defaults:   { _controller: HomeWorkBundle:Index:twig2 }